# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: validate
    jobs:
    - job: validate
      continueonerror: false
      steps:
      - task: TerraformInstaller@0
        displayname: 'install'
        inputs:
         terraformVersion: 'latest'
      - task: TerraformCLI@0
        displayname: 'init'
        inputs:
          command: 'init'
      - task: TerraformCLI@0
        displayname: 'validate'
        inputs:
          command: 'validate'

  - stage: plan
    dependsOn: [validate]
    condition: succeeded('validate')
    jobs:
    - job: validate
      continueonerror: false
      steps:
      - task: TerraformInstaller@0
        displayname: 'install'
        inputs:
         terraformVersion: 'latest'
      - task: TerraformCLI@0
        displayname: 'init'
        inputs:
          command: 'init'
      - task: TerraformCLI@0
        displayname: 'validate'
        inputs:
          command: 'validate'
      - task: TerraformCLI@0
        displayname: 'plan'
        inputs:
         command: 'plan'

